# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "UjN1uylM0lfVMHeddAl3El5tQNb4wMOLZeZbtfC/vP6GFouDNMG9lSvCV7IMcepCP5LS6VEuZwxvxJ3u9EiSGQ/bCLT3LKylwtia9RO+pVEKHlWwvQDCgo7UCpdROOBsW5/j8lkrSyUe18TluPCWE1/uloBzleV011E73eF3p64apBZ6RJsNw6iSfzHNZyXQOTWEgkt69cyr+72x0huEcrhnIVwfqSi2OXcF4EMP8TXdAlJAanN42QPQwxysVlPawUPMrbUNJS+MSPj8DdTugAb3iD9DpeNIUKzpbirUJ+lVVROChCTllzKUdNqiEYd0yzAuUsWGebWNf03HKIK+hYY2mcK4SF8/2ytGEwd1hLitvPyvEsIg/qI/VdQYAcgoJ5gryQOmQ005iNj+eOXMacgFm3LG0/1Zq08A2L6Jexu+8Y1QR1f9FrNT2SyZ3YMnHZmkW1MfCFZHOXwnhJ3NB1Nk+Pi0muYt6aZ/nf9UkolB4BOOrsHoTPvS2UiV0725LK3cURfyj6/pK38/5WFfg9h+oiGLbDDMNaqtvrcVHdR9tSaIR4xTPhiIcgrDcvbLRIOwkP3OiG0qYuC6b8JYIcQByTjqiRkeBzPCSY09wcuMPQO5M4a8BreSsY45Xl+7sVUF2eSnl8eubOb6G5aJ7hZp6DasTYTEif5UP25kask="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
