travis:
  secure:
    BINSTAR_TOKEN: yEZVxB3RaumW56mCpu56XGO9NOKh+ABQ9Pc6GmI6vZIe9RkUo6Fcus8EO/fRJGEl2+LSYQTIQX4IHjt3vEu18sBa/1Z4fgkcaLOjO3CTxjYKXr4nU4N4lvJke1LDvUmKtqQokXdEV0hwk2ad9bRjNHtNo8XyECAgYbZnIF8FFHM/nK8XKwPmCl3dTGK5vzI23Hu3YYMnVs8wghj8lEkrxw9rFmoY30ZWCBUUkf1JIP+FZS67yYoaJZGcoQB4xOWOD0aqmCiin+wjlmNDsmZ6BIXlvyW5jbi0dklhPhBzvjdssZ4Dc2O2WeZyI6IcLHr7KI+I5WOUxmZsLar2fek95k+fv2gruwj7kekTMbJ94O3SagFvAfmfiPWQUmq9+e40+GgUCLEFkBbkPyxjgpx+FXNeJqWyZk8KfikbAYL/iIxFS5Ssi/6WnRf3Cej+NdJjZdmckbCghcoFZRpg+YYt9FXkX2aMDrGFDtik3bcTJRtgmBLa1PZr8RSCP4VTuco5m6dr3+6/3BugycisoL45WM8L5sARSO/JL0+Ysd6gmg6AlStptDdbc25WRR28GSgKmT7QKIqwlms7f1+ms59fLmdfBRVN25mEadxIfctEmO3IWdrldVKmDh/cgXShTB1oPkI5QPYGcfMRZcWIJjmzkmuOncYB+cPhI9iw0aJ5J5w=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
