travis:
  secure:
    BINSTAR_TOKEN: UjN1uylM0lfVMHeddAl3El5tQNb4wMOLZeZbtfC/vP6GFouDNMG9lSvCV7IMcepCP5LS6VEuZwxvxJ3u9EiSGQ/bCLT3LKylwtia9RO+pVEKHlWwvQDCgo7UCpdROOBsW5/j8lkrSyUe18TluPCWE1/uloBzleV011E73eF3p64apBZ6RJsNw6iSfzHNZyXQOTWEgkt69cyr+72x0huEcrhnIVwfqSi2OXcF4EMP8TXdAlJAanN42QPQwxysVlPawUPMrbUNJS+MSPj8DdTugAb3iD9DpeNIUKzpbirUJ+lVVROChCTllzKUdNqiEYd0yzAuUsWGebWNf03HKIK+hYY2mcK4SF8/2ytGEwd1hLitvPyvEsIg/qI/VdQYAcgoJ5gryQOmQ005iNj+eOXMacgFm3LG0/1Zq08A2L6Jexu+8Y1QR1f9FrNT2SyZ3YMnHZmkW1MfCFZHOXwnhJ3NB1Nk+Pi0muYt6aZ/nf9UkolB4BOOrsHoTPvS2UiV0725LK3cURfyj6/pK38/5WFfg9h+oiGLbDDMNaqtvrcVHdR9tSaIR4xTPhiIcgrDcvbLRIOwkP3OiG0qYuC6b8JYIcQByTjqiRkeBzPCSY09wcuMPQO5M4a8BreSsY45Xl+7sVUF2eSnl8eubOb6G5aJ7hZp6DasTYTEif5UP25kask=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
